fn_brace_style = "SameLineWhere"
fn_return_indent = "WithWhereClause"
fn_args_density = "Compressed"
where_layout = "Horizontal"
format_strings = false
chain_one_line_max = 15
ideal_width = 100
take_source_hints = true
